# Generated by Django 4.0 on 2022-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_ratins_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
