# Generated by Django 4.0 on 2022-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
